### ISSUE TITLE
具体应该设置哪个呢？

### ISSUE THREAD

**Issue by zhanghm1995** [aglent/autoproxy#6]
您好，
我对这个Switchy Omega机制不是很熟悉，这个白名单、黑名单我具体应该设置哪个呢，能麻烦你附上你最终配置好的截图吗？README里的图片不显示了。

**Comment by aglent** [comment]
1、黑名单模式
新建情景模式 -> 选择自动切换模式
规则列表规则 选代理
默认情景模式 选直接连接
规则列表格式 选AutoProxy
规则列表网址 填https://raw.githubusercontent.com/aglent/autoproxy/master/gfwlist.pac
点击立即更新情景模式
图：https://tvax1.sinaimg.cn/large/591ad216ly1gowlqa49xwj212t15277g.jpg

2、白名单模式
新建情景模式 -> 选择自动切换模式
规则列表规则 选直接连接
默认情景模式 选代理
规则列表格式 选AutoProxy
规则列表网址 填https://raw.githubusercontent.com/aglent/autoproxy/master/whitelist.pac
点击立即更新情景模式
图：https://tvax2.sinaimg.cn/large/591ad216ly1gowlrcnyifj211z16yad3.jpg

**Comment by zhanghm1995** [comment]
那我实际使用的时候，应该优先选哪个模式呢？还是自己手动设置

**Comment by aglent** [comment]
> 
> 
> 那我实际使用的时候，应该优先选哪个模式呢？还是自己手动设置

看你是否需要加速国外正常网站的访问速度
没有这个需求，就用黑名单模式。
有这个需求，我推荐国内IP白名单模式，国内IP直连，国外IP走代理。

**Comment by zhanghm1995** [comment]
明白了，非常感谢你的回答~
