### ISSUE TITLE
国内ip白名单模式的proxy设置

### ISSUE THREAD

**Issue by MikoyChinese** [aglent/autoproxy#9]
国内白名单的proxy设置只能用pac内固定的么？可以指向switchomega自带的proxy内的设置么？

**Comment by aglent** [comment]
因为白名单pac里只有不走代理的域名，所以switchomega里需要设置switch profile 自动切换模式，并将规则列表设定为 [ 直接连接 ]，默认情景模式设定为已经建好的代理（即不在白名单内的其它域名走代理线路）。

**Comment by RamboXQ** [comment]
借楼问下。这个模式鼓捣了半天都没搞明白。我按你说的设置，看代理客户端的log发现不管国内外都是走代理呢。这个switch profile 自动切换模式并没有用到第一步建的CNIP的PAC文件呢。
![image](https://user-images.githubusercontent.com/17567680/144528616-a9a7bed0-d01b-4501-8109-5c61b7c7cf06.png)



> 因为白名单pac里只有不走代理的域名，所以switchomega里需要设置switch profile 自动切换模式，并将规则列表设定为 [ 直接连接 ]，默认情景模式设定为已经建好的代理（即不在白名单内的其它域名走代理线路）。

**Comment by aglent** [comment]
> 借楼问下。这个模式鼓捣了半天都没搞明白。我按你说的设置，看代理客户端的log发现不管国内外都是走代理呢。这个switch profile 自动切换模式并没有用到第一步建的CNIP的PAC文件呢。 ![image](https://user-images.githubusercontent.com/17567680/144528616-a9a7bed0-d01b-4501-8109-5c61b7c7cf06.png)
> 
> > 因为白名单pac里只有不走代理的域名，所以switchomega里需要设置switch profile 自动切换模式，并将规则列表设定为 [ 直接连接 ]，默认情景模式设定为已经建好的代理（即不在白名单内的其它域名走代理线路）。


如果你想用国内域名白名单模式，需要在图中的【Rule List URL】填上https://git.io/whitelistpac， 并勾选 AutoProxy。

如果你想用国内IP白名单模式，SwitchyOmega 扩展里新建 pac profile 模式，填写 PAC URL：https://git.io/chinaip

但是我看你用了CFW这个代理工具，因为它是本身就有IP分流功能，所以没必要那么麻烦，直接开启CFW的系统代理就可以了，无需SwitchyOmega 扩展。

**Comment by RamboXQ** [comment]
@aglent 感谢回复。CFW可以用。有的时候也想用下协议专用客户端，之前都是要扶墙时手动切换，用这个自动切换也方便很多，谢谢！
